export const API_DOC_SECTIONS = [
  {
    id: "auth",
    title: "Авторизация",
    description: "Вход, регистрация и завершение сессии.",
    endpoints: [
      {
        method: "POST",
        endpoint: "/auth/login",
        access: "public",
        purpose: "Авторизация пользователя.",
        body: ["email", "password"],
        response: ["user", "token", "message"],
      },
      {
        method: "POST",
        endpoint: "/auth/register",
        access: "public",
        purpose: "Регистрация нового пользователя.",
        body: ["firstName", "lastName", "email", "phone", "password"],
        response: ["user", "token", "message"],
      },
      {
        method: "POST",
        endpoint: "/auth/logout",
        access: "auth",
        purpose: "Выход из аккаунта и очистка сессии.",
        response: ["message"],
      },
    ],
  },
  {
    id: "profile",
    title: "Профиль",
    description: "Личный кабинет, аватар, пароль и заявка на роль сотрудника.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/profile",
        access: "auth",
        purpose: "Получение текущего профиля пользователя.",
        response: ["id", "name", "role", "avatar", "employeeRequest"],
      },
      {
        method: "PATCH",
        endpoint: "/profile",
        access: "auth",
        purpose: "Обновление имени и фамилии.",
        body: ["firstName", "lastName"],
        response: ["user", "message"],
      },
      {
        method: "POST",
        endpoint: "/profile/password",
        access: "auth",
        purpose: "Смена пароля.",
        body: ["oldPassword", "newPassword", "confirmPassword"],
        response: ["message"],
      },
      {
        method: "POST",
        endpoint: "/profile/avatar",
        access: "auth",
        purpose: "Загрузка аватара пользователя.",
        body: ["file(FormData)"],
        response: ["user", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/profile/avatar",
        access: "auth",
        purpose: "Удаление аватара из хранилища.",
        response: ["user", "message"],
      },
      {
        method: "POST",
        endpoint: "/profile/employee-request",
        access: "user",
        purpose: "Отправка заявки на переход из user в employee.",
        response: ["id", "status", "createdAt", "message"],
      },
    ],
  },
  {
    id: "appeals",
    title: "Обращения",
    description: "Создание, просмотр, редактирование и рабочие действия по обращениям.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/appeals",
        access: "auth",
        purpose: "Список обращений по роли и фильтрам.",
        query: ["role", "status", "statusGroup", "priority", "search", "page", "limit"],
        response: ["data[]", "meta(total, page, totalPages, statusCounts)"],
      },
      {
        method: "POST",
        endpoint: "/appeals",
        access: "auth",
        purpose: "Создание обращения с AI-анализом и отправкой на модерацию.",
        body: ["description", "location{x,y,address,label}", "photos[]", "appealId?"],
        response: ["appeal", "message"],
      },
      {
        method: "GET",
        endpoint: "/appeals/:id",
        access: "auth",
        purpose: "Получение детальной карточки обращения.",
        response: ["appeal", "timeline", "roadmap", "aiResult"],
      },
      {
        method: "PATCH",
        endpoint: "/appeals/:id",
        access: "auth",
        purpose: "Редактирование обращения в допустимом состоянии.",
        body: ["description?", "location?", "photos?", "category?"],
        response: ["appeal", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/appeals/:id",
        access: "auth",
        purpose: "Удаление обращения и связанных изображений.",
        response: ["message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/reserve",
        access: "auth",
        purpose: "Резервирование заранее известного id обращения.",
        response: ["appealId", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/recheck-ai",
        access: "admin|superadmin",
        purpose: "Повторный запуск AI-анализа обращения.",
        response: ["appeal", "aiResult", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/review",
        access: "admin|superadmin",
        purpose: "Решение по модерации обращения.",
        body: ["isOk", "moderationNote?"],
        response: ["appeal", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/assign",
        access: "admin|superadmin",
        purpose: "Назначение сотрудника и изменение данных обращения.",
        body: ["assignedEmployeeId?", "category?", "priority?", "deadlineAt?"],
        response: ["appeal", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/accept",
        access: "employee",
        purpose: "Принятие обращения сотрудником в работу.",
        response: ["appeal", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/work-submit",
        access: "employee",
        purpose: "Отправка результата работы сотрудника.",
        body: ["employeeNote", "fixedImages[]", "fixedLocation?"],
        response: ["appeal", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/final-check",
        access: "admin|superadmin",
        purpose: "Финальная проверка выполнения обращения.",
        body: ["isAccepted", "moderationNote?"],
        response: ["appeal", "message"],
      },
      {
        method: "POST",
        endpoint: "/appeals/:id/rate",
        access: "user",
        purpose: "Оценка завершённого обращения пользователем.",
        body: ["score", "comment?"],
        response: ["appeal", "message"],
      },
    ],
  },
  {
    id: "dashboard",
    title: "Дашборд",
    description: "Публичные и внутренние агрегированные данные для панели.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/dashboard/summary",
        access: "auth",
        purpose: "Краткая сводка по обращениям и ролям.",
        response: ["stats", "message"],
      },
      {
        method: "GET",
        endpoint: "/dashboard/heatmap",
        access: "auth",
        purpose: "Точки для тепловой карты обращений.",
        response: ["data[[x,y]]", "meta(total)"],
      },
      {
        method: "GET",
        endpoint: "/dashboard/appeals",
        access: "auth",
        purpose: "Короткий список последних обращений для панели.",
        query: ["limit"],
        response: ["data[]", "message"],
      },
    ],
  },
  {
    id: "blob",
    title: "Файлы",
    description: "Загрузка, просмотр и удаление файлов в blob-хранилище.",
    endpoints: [
      {
        method: "POST",
        endpoint: "/blob/upload",
        access: "auth",
        purpose: "Загрузка одного или нескольких файлов в нужную папку.",
        body: ["file(FormData)", "folder?"],
        response: ["files[]", "message"],
      },
      {
        method: "GET",
        endpoint: "/blob/list",
        access: "auth",
        purpose: "Получение списка файлов по папке.",
        query: ["folder", "limit?"],
        response: ["files[]", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/blob/delete",
        access: "auth",
        purpose: "Удаление файла из blob-хранилища.",
        body: ["pathname"],
        response: ["message"],
      },
    ],
  },
  {
    id: "content",
    title: "Контент",
    description: "Публичный контент платформы.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/faq",
        access: "public",
        purpose: "Публичный список FAQ.",
        response: ["data[]", "message"],
      },
      {
        method: "GET",
        endpoint: "/about-us",
        access: "public",
        purpose: "Данные страницы о проекте.",
        response: ["data", "message"],
      },
    ],
  },
  {
    id: "admin",
    title: "Администрирование",
    description: "Пользователи, сотрудники, категории и FAQ для панели управления.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/admin/users",
        access: "admin|superadmin",
        purpose: "Список пользователей по роли.",
        query: ["role(user|employee)", "search?"],
        response: ["data[]", "meta"],
      },
      {
        method: "GET",
        endpoint: "/admin/users/:id",
        access: "admin|superadmin",
        purpose: "Детальная страница пользователя и его обращений.",
        query: ["page?", "limit?"],
        response: ["user", "appeals[]", "stats", "meta"],
      },
      {
        method: "GET",
        endpoint: "/admin/staff/:id",
        access: "admin|superadmin",
        purpose: "Детальная страница сотрудника и его обращений.",
        query: ["page?", "limit?", "statusGroup?"],
        response: ["employee", "appeals[]", "stats", "meta"],
      },
      {
        method: "POST",
        endpoint: "/admin/staff/:id/demote",
        access: "admin|superadmin",
        purpose: "Понижение сотрудника до user при отсутствии активных обращений.",
        response: ["id", "role", "message"],
      },
      {
        method: "GET",
        endpoint: "/admin/employee-requests",
        access: "admin|superadmin",
        purpose: "Список заявок на роль сотрудника.",
        query: ["status(pending|approved|rejected|all)"],
        response: ["data[]", "meta(total, filteredTotal, statusCounts)"],
      },
      {
        method: "PATCH",
        endpoint: "/admin/employee-requests/:id",
        access: "admin|superadmin",
        purpose: "Одобрение или отклонение заявки на сотрудника.",
        body: ["status(approved|rejected)", "adminComment?"],
        response: ["data", "message"],
      },
      {
        method: "GET",
        endpoint: "/admin/categories",
        access: "admin|superadmin",
        purpose: "Список категорий обращений.",
        response: ["data[]", "message"],
      },
      {
        method: "POST",
        endpoint: "/admin/categories",
        access: "admin|superadmin",
        purpose: "Создание новой категории.",
        body: ["key", "name", "description", "subcategories[]", "order?"],
        response: ["category", "message"],
      },
      {
        method: "PATCH",
        endpoint: "/admin/categories/:id",
        access: "admin|superadmin",
        purpose: "Редактирование категории.",
        body: ["name?", "description?", "subcategories?", "isActive?"],
        response: ["category", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/admin/categories/:id",
        access: "admin|superadmin",
        purpose: "Удаление категории.",
        response: ["message"],
      },
      {
        method: "GET",
        endpoint: "/admin/faq",
        access: "admin|superadmin",
        purpose: "Управление FAQ.",
        response: ["data[]", "message"],
      },
      {
        method: "POST",
        endpoint: "/admin/faq",
        access: "admin|superadmin",
        purpose: "Создание FAQ-записи.",
        body: ["question", "answer", "category", "order?", "isActive?"],
        response: ["faq", "message"],
      },
      {
        method: "PATCH",
        endpoint: "/admin/faq/:id",
        access: "admin|superadmin",
        purpose: "Редактирование FAQ-записи.",
        body: ["question?", "answer?", "category?", "order?", "isActive?"],
        response: ["faq", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/admin/faq/:id",
        access: "admin|superadmin",
        purpose: "Удаление FAQ-записи.",
        response: ["message"],
      },
    ],
  },
  {
    id: "ai",
    title: "AI и промты",
    description: "Управление промтами и тестовый запуск AI без записи в базу.",
    endpoints: [
      {
        method: "GET",
        endpoint: "/ai/prompts",
        access: "admin|superadmin",
        purpose: "Список AI-промтов.",
        response: ["data[]", "message"],
      },
      {
        method: "POST",
        endpoint: "/ai/prompts",
        access: "admin|superadmin",
        purpose: "Создание нового AI-промта.",
        body: ["key", "title", "systemPrompt", "userTemplate", "guardrails", "isActive?"],
        response: ["prompt", "message"],
      },
      {
        method: "PATCH",
        endpoint: "/ai/prompts/:id",
        access: "admin|superadmin",
        purpose: "Редактирование AI-промта.",
        body: ["title?", "systemPrompt?", "userTemplate?", "guardrails?", "isActive?"],
        response: ["prompt", "message"],
      },
      {
        method: "DELETE",
        endpoint: "/ai/prompts/:id",
        access: "admin|superadmin",
        purpose: "Удаление AI-промта.",
        response: ["message"],
      },
      {
        method: "GET",
        endpoint: "/ai/prompts/test",
        access: "admin|superadmin",
        purpose: "Получение демо-данных для теста AI.",
        response: ["appeals[]", "prompts[]", "message"],
      },
      {
        method: "POST",
        endpoint: "/ai/prompts/test",
        access: "admin|superadmin",
        purpose: "Демо-запуск AI на обращении без сохранения в базу.",
        body: ["appealId", "promptIds?"],
        response: ["result", "raw", "decision", "message"],
      },
    ],
  },
];

export const API_ACCESS_META = {
  public: { label: "Публичный", tone: "is-public" },
  auth: { label: "Авторизованный", tone: "is-auth" },
  user: { label: "User", tone: "is-user" },
  employee: { label: "Employee", tone: "is-employee" },
  "admin|superadmin": { label: "Admin / SuperAdmin", tone: "is-admin" },
};
